version: '3.7'

services:
  ecommerce:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - target: 3306
  social:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - target: 27017
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - target: 27017
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
